### ISSUE TITLE
Error: invalid or unsupported assembly accession 

### ISSUE THREAD

**Issue by swelbo** [EvolBioInf/neighbors#3]
Hello! 

I am having a problem with downloading targets and neighbours with datasets. I have updated neighbors and datasets but this hasn't solved the issue. I'm not sure if its an issue with the list of targets/neighbors have generated using neighbors or an issue with the datasets tool. When i run datasets on a single genome accession it seems to work, for example GCA_029537415.1. So maybe an issue with datasets and its ability to handle a txt file? 

Command:

datasets download genome accession \
    --inputfile targets.txt \
    --assembly-level complete \
    --exclude-atypical \
    --dehydrated \
    --filename tdata.zip
 
Output: 

Error: invalid or unsupported assembly accession: -

Use datasets download genome accession <command> --help for detailed help about a command.

Thanks 

Tom

**Comment by swelbo** [comment]
A little digging into our workflow it looks like its this step is causing the issue - Generating list if targets and neighbors. 

printf 562 | neighbors -l neidb > acc.txt 


output (acc.txt)

n         GCA_019840185.1
n         GCA_019839605.1
n         GCA_024733345.1
n         GCA_019839365.1
n         GCA_019839465.1
n         GCA_036296105.1
n         -

We seem to be getting a dash as an accession for neighbors (or targets depending on ncbi_id). This is then causing the issue with running datasets. This suddenly started happening without updating neighbors, but we are working within and open environment so something else may have been updated with out knowing.

**Comment by haubold** [comment]
Thank pointing out this problem. However, I believe I already fixed this on 4th of April, so `git pull` and `make clean && make` should get rid of the hyphens.

**Comment by swelbo** [comment]
Thanks for the reply! 

I actually removed the old version and re-cloned the repo. 

commit 987cb30384c57a5d2c7c35c47572f06287e9ec9f (HEAD -> main, origin/main, origin/HEAD)
Author: Bernhard Haubold <haubold@evolbio.mpg.de>
Date:   Sun Jun 2 11:39:14 2024 +0200

neighbors v2.0-23-g987cb30, 2_Jun_2024

I still get the hyphan but for only some taxa ID - 562 and 1423 is an example for me

**Comment by haubold** [comment]
I _thought_ I had fixed this on 4th April... However, in that fix I had assumed that hyphens represent empty queries for genome accessions and hence can only occupy the first position in an accessions list. In the latest version of the NCBI data used to build the `neighbors` database, hyphens can appear anywhere in a list of genome accessions. So now I search the full accessions list of each target and neighbor and remove any hyphens. That should do the trick.

**Comment by swelbo** [comment]
fixed it. thank you so much!
